/* 48 个英语音标结构化数据
 * 由 phonetic_words.json + 音标符号表生成，资源文件均为相对路径。
 * 分类: long 长元音 / short 短元音 / diphthong 双元音 / voiceless 清辅音 / voiced 浊辅音 */

const CATEGORY_LABELS = {
  long: '元音 · 长元音',
  short: '元音 · 短元音',
  diphthong: '元音 · 双元音',
  voiceless: '辅音 · 清辅音',
  voiced: '辅音 · 浊辅音',
};

const PHONETICS = [
  { id: 1, symbol: "/i:/", category: "long",
    audio: "words-voice/word-long_vowel_i.mp3",
    video: "video/phonetic-1.mp4",
    words: [
      { word: "bee", audio: "words-voice/word-bee.mp3" },
      { word: "we", audio: "words-voice/word-we.mp3" },
      { word: "read", audio: "words-voice/word-read.mp3" },
    ] },
  { id: 2, symbol: "/ɜ:/", category: "long",
    audio: "words-voice/word-long_vowel_3.mp3",
    video: "video/phonetic-2.mp4",
    words: [
      { word: "bird", audio: "words-voice/word-bird.mp3" },
      { word: "word", audio: "words-voice/word-word.mp3" },
      { word: "work", audio: "words-voice/word-work.mp3" },
    ] },
  { id: 3, symbol: "/ɑ:/", category: "long",
    audio: "words-voice/word-long_vowel_2.mp3",
    video: "video/phonetic-3.mp4",
    words: [
      { word: "mark", audio: "words-voice/word-mark.mp3" },
      { word: "shark", audio: "words-voice/word-shark.mp3" },
      { word: "father", audio: "words-voice/word-father.mp3" },
    ] },
  { id: 4, symbol: "/ɔ:/", category: "long",
    audio: "words-voice/word-long_vowel_4.mp3",
    video: "video/phonetic-4.mp4",
    words: [
      { word: "caught", audio: "words-voice/word-caught.mp3" },
      { word: "walk", audio: "words-voice/word-walk.mp3" },
      { word: "board", audio: "words-voice/word-board.mp3" },
    ] },
  { id: 5, symbol: "/u:/", category: "long",
    audio: "words-voice/word-long_vowel_u.mp3",
    video: "video/phonetic-5.mp4",
    words: [
      { word: "cool", audio: "words-voice/word-cool.mp3" },
      { word: "rude", audio: "words-voice/word-rude.mp3" },
      { word: "tooth", audio: "words-voice/word-tooth.mp3" },
    ] },
  { id: 6, symbol: "/ɪ/", category: "short",
    audio: "words-voice/word-short_vowel_I.mp3",
    video: "video/phonetic-6.mp4",
    words: [
      { word: "little", audio: "words-voice/word-little.mp3" },
      { word: "sit", audio: "words-voice/word-sit.mp3" },
      { word: "fish", audio: "words-voice/word-fish.mp3" },
    ] },
  { id: 7, symbol: "/e/", category: "short",
    audio: "words-voice/word-short_vowel_e.mp3",
    video: "video/phonetic-7.mp4",
    words: [
      { word: "bed", audio: "words-voice/word-bed.mp3" },
      { word: "red", audio: "words-voice/word-red.mp3" },
      { word: "egg", audio: "words-voice/word-egg.mp3" },
    ] },
  { id: 8, symbol: "/æ/", category: "short",
    audio: "words-voice/word-short_vowel_5.mp3",
    video: "video/phonetic-8.mp4",
    words: [
      { word: "mass", audio: "words-voice/word-mass.mp3" },
      { word: "ant", audio: "words-voice/word-ant.mp3" },
      { word: "lamb", audio: "words-voice/word-lamb.mp3" },
    ] },
  { id: 9, symbol: "/ə/", category: "short",
    audio: "words-voice/word-short_vowel_6.mp3",
    video: "video/phonetic-9.mp4",
    words: [
      { word: "center", audio: "words-voice/word-center.mp3" },
      { word: "panda", audio: "words-voice/word-panda.mp3" },
      { word: "actor", audio: "words-voice/word-actor.mp3" },
    ] },
  { id: 10, symbol: "/ʌ/", category: "short",
    audio: "words-voice/word-short_vowel_7.mp3",
    video: "video/phonetic-10.mp4",
    words: [
      { word: "cup", audio: "words-voice/word-cup.mp3" },
      { word: "bus", audio: "words-voice/word-bus.mp3" },
      { word: "sun", audio: "words-voice/word-sun.mp3" },
    ] },
  { id: 11, symbol: "/ɒ/", category: "short",
    audio: "words-voice/word-short_vowel_8.mp3",
    video: "video/phonetic-11.mp4",
    words: [
      { word: "dog", audio: "words-voice/word-dog.mp3" },
      { word: "box", audio: "words-voice/word-box.mp3" },
      { word: "stop", audio: "words-voice/word-stop.mp3" },
    ] },
  { id: 12, symbol: "/ʊ/", category: "short",
    audio: "words-voice/word-short_vowel_9.mp3",
    video: "video/phonetic-12.mp4",
    words: [
      { word: "book", audio: "words-voice/word-book.mp3" },
      { word: "good", audio: "words-voice/word-good.mp3" },
      { word: "full", audio: "words-voice/word-full.mp3" },
    ] },
  { id: 13, symbol: "/eɪ/", category: "diphthong",
    audio: "words-voice/word-two_vowel_ei.mp3",
    video: "video/phonetic-13.mp4",
    words: [
      { word: "wait", audio: "words-voice/word-wait.mp3" },
      { word: "late", audio: "words-voice/word-late.mp3" },
      { word: "hate", audio: "words-voice/word-hate.mp3" },
    ] },
  { id: 14, symbol: "/aɪ/", category: "diphthong",
    audio: "words-voice/word-two_vowel_1.mp3",
    video: "video/phonetic-14.mp4",
    words: [
      { word: "my", audio: "words-voice/word-my.mp3" },
      { word: "why", audio: "words-voice/word-why.mp3" },
      { word: "write", audio: "words-voice/word-write.mp3" },
    ] },
  { id: 15, symbol: "/ɔɪ/", category: "diphthong",
    audio: "words-voice/word-two_vowel_4.mp3",
    video: "video/phonetic-15.mp4",
    words: [
      { word: "noise", audio: "words-voice/word-noise.mp3" },
      { word: "point", audio: "words-voice/word-point.mp3" },
      { word: "oil", audio: "words-voice/word-oil.mp3" },
    ] },
  { id: 16, symbol: "/aʊ/", category: "diphthong",
    audio: "words-voice/word-two_vowel_2.mp3",
    video: "video/phonetic-16.mp4",
    words: [
      { word: "mouse", audio: "words-voice/word-mouse.mp3" },
      { word: "town", audio: "words-voice/word-town.mp3" },
      { word: "cloud", audio: "words-voice/word-cloud.mp3" },
    ] },
  { id: 17, symbol: "/əʊ/", category: "diphthong",
    audio: "words-voice/word-two_vowel_5.mp3",
    video: "video/phonetic-17.mp4",
    words: [
      { word: "pose", audio: "words-voice/word-pose.mp3" },
      { word: "mode", audio: "words-voice/word-mode.mp3" },
      { word: "know", audio: "words-voice/word-know.mp3" },
    ] },
  { id: 18, symbol: "/ɪə/", category: "diphthong",
    audio: "words-voice/word-two_vowel_6.mp3",
    video: "video/phonetic-18.mp4",
    words: [
      { word: "beer", audio: "words-voice/word-beer.mp3" },
      { word: "mere", audio: "words-voice/word-mere.mp3" },
      { word: "deer", audio: "words-voice/word-deer.mp3" },
    ] },
  { id: 19, symbol: "/eə/", category: "diphthong",
    audio: "words-voice/word-two_vowel_3.mp3",
    video: "video/phonetic-19.mp4",
    words: [
      { word: "bear", audio: "words-voice/word-bear.mp3" },
      { word: "wear", audio: "words-voice/word-wear.mp3" },
      { word: "fare", audio: "words-voice/word-fare.mp3" },
    ] },
  { id: 20, symbol: "/ʊə/", category: "diphthong",
    audio: "words-voice/word-two_vowel_7.mp3",
    video: "video/phonetic-20.mp4",
    words: [
      { word: "poor", audio: "words-voice/word-poor.mp3" },
      { word: "tour", audio: "words-voice/word-tour.mp3" },
      { word: "pure", audio: "words-voice/word-pure.mp3" },
    ] },
  { id: 21, symbol: "/p/", category: "voiceless",
    audio: "words-voice/word-consonant_p.mp3",
    video: "video/phonetic-21.mp4",
    words: [
      { word: "sip", audio: "words-voice/word-sip.mp3" },
      { word: "put", audio: "words-voice/word-put.mp3" },
      { word: "cup", audio: "words-voice/word-cup.mp3" },
    ] },
  { id: 22, symbol: "/t/", category: "voiceless",
    audio: "words-voice/word-consonant_t.mp3",
    video: "video/phonetic-22.mp4",
    words: [
      { word: "tomorrow", audio: "words-voice/word-tomorrow.mp3" },
      { word: "today", audio: "words-voice/word-today.mp3" },
      { word: "top", audio: "words-voice/word-top.mp3" },
    ] },
  { id: 23, symbol: "/k/", category: "voiceless",
    audio: "words-voice/word-consonant_k.mp3",
    video: "video/phonetic-23.mp4",
    words: [
      { word: "cat", audio: "words-voice/word-cat.mp3" },
      { word: "cup", audio: "words-voice/word-cup.mp3" },
      { word: "card", audio: "words-voice/word-card.mp3" },
    ] },
  { id: 24, symbol: "/f/", category: "voiceless",
    audio: "words-voice/word-consonant_f.mp3",
    video: "video/phonetic-24.mp4",
    words: [
      { word: "fish", audio: "words-voice/word-fish.mp3" },
      { word: "free", audio: "words-voice/word-free.mp3" },
      { word: "floor", audio: "words-voice/word-floor.mp3" },
    ] },
  { id: 25, symbol: "/s/", category: "voiceless",
    audio: "words-voice/word-consonant_s.mp3",
    video: "video/phonetic-25.mp4",
    words: [
      { word: "nice", audio: "words-voice/word-nice.mp3" },
      { word: "bus", audio: "words-voice/word-bus.mp3" },
      { word: "sit", audio: "words-voice/word-sit.mp3" },
    ] },
  { id: 26, symbol: "/ʃ/", category: "voiceless",
    audio: "words-voice/word-consonant_1.mp3",
    video: "video/phonetic-26.mp4",
    words: [
      { word: "ship", audio: "words-voice/word-ship.mp3" },
      { word: "fish", audio: "words-voice/word-fish.mp3" },
      { word: "shirt", audio: "words-voice/word-shirt.mp3" },
    ] },
  { id: 27, symbol: "/θ/", category: "voiceless",
    audio: "words-voice/word-consonant_2.mp3",
    video: "video/phonetic-27.mp4",
    words: [
      { word: "path", audio: "words-voice/word-path.mp3" },
      { word: "think", audio: "words-voice/word-think.mp3" },
      { word: "math", audio: "words-voice/word-math.mp3" },
    ] },
  { id: 28, symbol: "/h/", category: "voiceless",
    audio: "words-voice/word-consonant_h.mp3",
    video: "video/phonetic-28.mp4",
    words: [
      { word: "hut", audio: "words-voice/word-hut.mp3" },
      { word: "hello", audio: "words-voice/word-hello.mp3" },
      { word: "home", audio: "words-voice/word-home.mp3" },
    ] },
  { id: 29, symbol: "/tʃ/", category: "voiceless",
    audio: "words-voice/word-consonant_6.mp3",
    video: "video/phonetic-29.mp4",
    words: [
      { word: "chick", audio: "words-voice/word-chick.mp3" },
      { word: "coach", audio: "words-voice/word-coach.mp3" },
      { word: "rich", audio: "words-voice/word-rich.mp3" },
    ] },
  { id: 30, symbol: "/ts/", category: "voiceless",
    audio: "words-voice/word-consonant_ts.mp3",
    video: "video/phonetic-30.mp4",
    words: [
      { word: "eats", audio: "words-voice/word-eats.mp3" },
      { word: "cats", audio: "words-voice/word-cats.mp3" },
      { word: "gifts", audio: "words-voice/word-gifts.mp3" },
    ] },
  { id: 31, symbol: "/tr/", category: "voiceless",
    audio: "words-voice/word-consonant_tr.mp3",
    video: "video/phonetic-31.mp4",
    words: [
      { word: "track", audio: "words-voice/word-track.mp3" },
      { word: "tree", audio: "words-voice/word-tree.mp3" },
      { word: "trill", audio: "words-voice/word-trill.mp3" },
    ] },
  { id: 32, symbol: "/b/", category: "voiced",
    audio: "words-voice/word-consonant_b.mp3",
    video: "video/phonetic-32.mp4",
    words: [
      { word: "bread", audio: "words-voice/word-bread.mp3" },
      { word: "club", audio: "words-voice/word-club.mp3" },
      { word: "lab", audio: "words-voice/word-lab.mp3" },
    ] },
  { id: 33, symbol: "/d/", category: "voiced",
    audio: "words-voice/word-consonant_d.mp3",
    video: "video/phonetic-33.mp4",
    words: [
      { word: "dog", audio: "words-voice/word-dog.mp3" },
      { word: "card", audio: "words-voice/word-card.mp3" },
      { word: "bed", audio: "words-voice/word-bed.mp3" },
    ] },
  { id: 34, symbol: "/g/", category: "voiced",
    audio: "words-voice/word-consonant_g.mp3",
    video: "video/phonetic-34.mp4",
    words: [
      { word: "egg", audio: "words-voice/word-egg.mp3" },
      { word: "dig", audio: "words-voice/word-dig.mp3" },
      { word: "gate", audio: "words-voice/word-gate.mp3" },
    ] },
  { id: 35, symbol: "/v/", category: "voiced",
    audio: "words-voice/word-consonant_v.mp3",
    video: "video/phonetic-35.mp4",
    words: [
      { word: "very", audio: "words-voice/word-very.mp3" },
      { word: "dove", audio: "words-voice/word-dove.mp3" },
      { word: "ever", audio: "words-voice/word-ever.mp3" },
    ] },
  { id: 36, symbol: "/z/", category: "voiced",
    audio: "words-voice/word-consonant_z.mp3",
    video: "video/phonetic-36.mp4",
    words: [
      { word: "seize", audio: "words-voice/word-seize.mp3" },
      { word: "zero", audio: "words-voice/word-zero.mp3" },
      { word: "size", audio: "words-voice/word-size.mp3" },
    ] },
  { id: 37, symbol: "/ʒ/", category: "voiced",
    audio: "words-voice/word-consonant_3.mp3",
    video: "video/phonetic-37.mp4",
    words: [
      { word: "decision", audio: "words-voice/word-decision.mp3" },
      { word: "television", audio: "words-voice/word-television.mp3" },
      { word: "leisure", audio: "words-voice/word-leisure.mp3" },
    ] },
  { id: 38, symbol: "/ð/", category: "voiced",
    audio: "words-voice/word-consonant_5.mp3",
    video: "video/phonetic-38.mp4",
    words: [
      { word: "they", audio: "words-voice/word-they.mp3" },
      { word: "those", audio: "words-voice/word-those.mp3" },
      { word: "other", audio: "words-voice/word-other.mp3" },
    ] },
  { id: 39, symbol: "/r/", category: "voiced",
    audio: "words-voice/word-consonant_r.mp3",
    video: "video/phonetic-39.mp4",
    words: [
      { word: "read", audio: "words-voice/word-read.mp3" },
      { word: "grass", audio: "words-voice/word-grass.mp3" },
      { word: "write", audio: "words-voice/word-write.mp3" },
    ] },
  { id: 40, symbol: "/dʒ/", category: "voiced",
    audio: "words-voice/word-consonant_7.mp3",
    video: "video/phonetic-40.mp4",
    words: [
      { word: "jam", audio: "words-voice/word-jam.mp3" },
      { word: "bridge", audio: "words-voice/word-bridge.mp3" },
      { word: "July", audio: "words-voice/word-July.mp3" },
    ] },
  { id: 41, symbol: "/dz/", category: "voiced",
    audio: "words-voice/word-consonant_dz.mp3",
    video: "video/phonetic-41.mp4",
    words: [
      { word: "beds", audio: "words-voice/word-beds.mp3" },
      { word: "adds", audio: "words-voice/word-adds.mp3" },
      { word: "friends", audio: "words-voice/word-friends.mp3" },
    ] },
  { id: 42, symbol: "/dr/", category: "voiced",
    audio: "words-voice/word-consonant_dr.mp3",
    video: "video/phonetic-42.mp4",
    words: [
      { word: "dress", audio: "words-voice/word-dress.mp3" },
      { word: "drink", audio: "words-voice/word-drink.mp3" },
      { word: "dream", audio: "words-voice/word-dream.mp3" },
    ] },
  { id: 43, symbol: "/m/", category: "voiced",
    audio: "words-voice/word-consonant_m.mp3",
    video: "video/phonetic-43.mp4",
    words: [
      { word: "smart", audio: "words-voice/word-smart.mp3" },
      { word: "move", audio: "words-voice/word-move.mp3" },
      { word: "mud", audio: "words-voice/word-mud.mp3" },
    ] },
  { id: 44, symbol: "/n/", category: "voiced",
    audio: "words-voice/word-consonant_n.mp3",
    video: "video/phonetic-44.mp4",
    words: [
      { word: "no", audio: "words-voice/word-no.mp3" },
      { word: "hunt", audio: "words-voice/word-hunt.mp3" },
      { word: "find", audio: "words-voice/word-find.mp3" },
    ] },
  { id: 45, symbol: "/ŋ/", category: "voiced",
    audio: "words-voice/word-consonant_4.mp3",
    video: "video/phonetic-45.mp4",
    words: [
      { word: "spring", audio: "words-voice/word-spring.mp3" },
      { word: "sing", audio: "words-voice/word-sing.mp3" },
      { word: "ink", audio: "words-voice/word-ink.mp3" },
    ] },
  { id: 46, symbol: "/l/", category: "voiced",
    audio: "words-voice/word-consonant_l.mp3",
    video: "video/phonetic-46.mp4",
    words: [
      { word: "line", audio: "words-voice/word-line.mp3" },
      { word: "pool", audio: "words-voice/word-pool.mp3" },
      { word: "alive", audio: "words-voice/word-alive.mp3" },
    ] },
  { id: 47, symbol: "/w/", category: "voiced",
    audio: "words-voice/word-consonant_w.mp3",
    video: "video/phonetic-47.mp4",
    words: [
      { word: "work", audio: "words-voice/word-work.mp3" },
      { word: "wood", audio: "words-voice/word-wood.mp3" },
      { word: "what", audio: "words-voice/word-what.mp3" },
    ] },
  { id: 48, symbol: "/j/", category: "voiced",
    audio: "words-voice/word-consonant_j.mp3",
    video: "video/phonetic-48.mp4",
    words: [
      { word: "yell", audio: "words-voice/word-yell.mp3" },
      { word: "yak", audio: "words-voice/word-yak.mp3" },
      { word: "youth", audio: "words-voice/word-youth.mp3" },
    ] },
];

